### ISSUE TITLE
OSX 14.2.1 Library not loaded: @rpath/libz.dylib

### ISSUE THREAD

**Issue by slpixe** [vivictorg/vivictpp#61]
Hiya, Tried installing and running vivictpp for the first time on OSX, but ran into the following issue and attempts to fix

Command: `vivictpp file1.mov`
Error: `dyld[36151]: Library not loaded: @rpath/libz.dylib`

I installed vivictpp via brew:
- brew install --overwrite python@3.12
- brew tap vivictorg/vivictpp
- brew install vivictpp

<img width="876" alt="Screenshot 2024-03-04 at 11 58 14" src="https://github.com/vivictorg/vivictpp/assets/385692/a97d3f21-0b8d-4848-b50d-2e31a0ff090c">

- brew install zlib

```
otool -L /opt/homebrew/bin/vivictpp
/opt/homebrew/bin/vivictpp:
	@rpath/libz.dylib (compatibility version 0.0.0, current version 0.0.0)
```

`echo $DYLD_LIBRARY_PATH` - returns empty

```
find /opt/homebrew/ -name "libz.dylib"
/opt/homebrew//Cellar/zlib/1.3.1/lib/libz.dylib
```

```
install_name_tool -add_rpath /usr/local/Cellar/zlib/1.3.1/lib /opt/homebrew/bin/vivictpp
```

```
vivictpp p6c40.mkv
zsh: killed     vivictpp p6c40.mkv
```

**Comment by bc-lee** [comment]
I encountered the same error when I tried installing `vivictpp` via a Homebrew tap. For reference, `otool` is analogous to `ldd` on Linux and displays the shared libraries that a binary depends on.

```
$ otool -L /opt/homebrew/bin/vivictpp
/opt/homebrew/bin/vivictpp:
	@rpath/libz.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/homebrew/opt/sdl2/lib/libSDL2-2.0.0.dylib (compatibility version 3001.0.0, current version 3001.3.0)
	/opt/homebrew/opt/sdl2_ttf/lib/libSDL2_ttf-2.0.0.dylib (compatibility version 2201.0.0, current version 2201.0.0)
	/opt/homebrew/opt/ffmpeg/lib/libavformat.61.dylib (compatibility version 61.0.0, current version 61.1.100)
	/opt/homebrew/opt/ffmpeg/lib/libavcodec.61.dylib (compatibility version 61.0.0, current version 61.3.100)
	/opt/homebrew/opt/ffmpeg/lib/libavutil.59.dylib (compatibility version 59.0.0, current version 59.8.100)
	/opt/homebrew/opt/ffmpeg/lib/libavfilter.10.dylib (compatibility version 10.0.0, current version 10.1.100)
	/opt/homebrew/opt/ffmpeg/lib/libswscale.8.dylib (compatibility version 8.0.0, current version 8.1.100)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1700.255.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1345.100.2)
```

As you can see, `vivictpp` relies on `libz.dylib`, a shared library. `vivictpp` has several dependencies, many of which are built from source. In the [subprojects](https://github.com/vivictorg/vivictpp/tree/8b0bc4b5f5835cf51efbe157ad9e508c83bc0e22/subprojects) directory, several files ending with `.wrap` exist, indicating that `vivictpp` uses the [meson wrap](https://mesonbuild.com/Wrap-dependency-system-manual.html) feature, and includes zlib.

Unfortunately, `vivictpp` attempts to build zlib from source, despite zlib being almost a system library on Linux, and similarly provided by the system on macOS. If the maintainers of `vivictpp` are intent on building zlib from source, it should ideally be built as a static library or shipped as a shared library.

My solution involves building `vivictpp` from source with some modifications. If I were proficient with Meson, I would remove zlib entirely and use the system version; however, I prefer to make minimal modifications due to convenience.

1) Update the `subprojects/zlib.wrap` file to use a newer version of the zlib patch file:

```
[wrap-file]
directory = zlib-1.2.13
source_url = http://zlib.net/fossils/zlib-1.2.13.tar.gz
source_fallback_url = https://github.com/mesonbuild/wrapdb/releases/download/zlib_1.2.13-4/zlib-1.2.13.tar.gz
source_filename = zlib-1.2.13.tar.gz
source_hash = b3a24de97a8fdbc835b9833169501030b8977031bcb54b3b3ac13740f846ab30
patch_filename = zlib_1.2.13-4_patch.zip
patch_url = https://wrapdb.mesonbuild.com/v2/zlib_1.2.13-4/get_patch
patch_hash = 19636b7807e679b92240bc7a99aed85d1be908a45430b12c7687a825cb499d5e
wrapdb_version = 1.2.13-4

[provide]
zlib = zlib_dep
```

The previous version (`zlib_1.2.13-2_patch.zip`) did not support static libraries effectively.

2) Build zlib as a static library by setting the `--default-library=static` option in the Meson setup command:

`$ meson setup builddir --default-library=static`

Afterward, I obtained a binary statically linked with `libz.a`:

```
$ find builddir -name "libz*"
builddir/subprojects/zlib-1.2.13/libz.a
builddir/subprojects/zlib-1.2.13/libz.a.p
$ otool -L builddir/vivictpp
builddir/vivictpp:
	/opt/homebrew/opt/sdl2/lib/libSDL2-2.0.0.dylib (compatibility version 3001.0.0, current version 3001.3.0)
	/opt/homebrew/opt/sdl2_ttf/lib/libSDL2_ttf-2.0.0.dylib (compatibility version 2201.0.0, current version 2201.0.0)
	/opt/homebrew/opt/ffmpeg/lib/libavformat.61.dylib (compatibility version 61.0.0, current version 61.1.100)
	/opt/homebrew/opt/ffmpeg/lib/libavcodec.61.dylib (compatibility version 61.0.0, current version 61.3.100)
	/opt/homebrew/opt/ffmpeg/lib/libavutil.59.dylib (compatibility version 59.0.0, current version 59.8.100)
	/opt/homebrew/opt/ffmpeg/lib/libavfilter.10.dylib (compatibility version 10.0.0, current version 10.1.100)
	/opt/homebrew/opt/ffmpeg/lib/libswscale.8.dylib (compatibility version 8.0.0, current version 8.1.100)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1600.157.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.61.1)
```

I hope this helps, and I also hope the maintainers of `vivictpp` will address this issue.

**Comment by grusell** [comment]
Apologies for the late reply, and thank you both for reporting and looking into this issue respectively. I will look into changing the build script to use the system zlib-library if possible. Can't remember if there was a reason I didn't configure it to do that in the first place.

**Comment by grusell** [comment]
With the newly released 1.1.0, vivictpp uses zlib from the system per default. @bc-lee @slpixe if you could verify that this indeed fixes the issue it would be apreciated.

**Comment by bc-lee** [comment]
Thanks. I tried two ways to verify this: building the project from source and installing it from a Homebrew tap. Both methods worked fine. Thanks for the fix.

**Comment by grusell** [comment]
Excellent, thanks for verifying the fix!
